# Generated by Django 5.0.3 on 2024-05-16 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0002_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='Icreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(choices=[('Deskripsi fitur', 'Deskripsi fitur'), ('Deskripsi label', 'Deskripsi label')], max_length=100)),
                ('isideskripsi', models.TextField(verbose_name='')),
                ('kategori', models.CharField(choices=[('klasifikasi', 'Klasifikasi'), ('prediksi_numerik', 'Prediksi Numerik'), ('prediksi_probabilistik', 'Prediksi Probabilistik'), ('deteksi', 'Deteksi'), ('rekognisi', 'Rekognisi')], max_length=30)),
                ('tanggal_mulai_pemodelan', models.DateField()),
                ('tanggal_selesai_pemodelan', models.DateField()),
                ('status_penyelesaian', models.CharField(choices=[('selesai', 'Selesai'), ('berlangsung', 'Berlangsung'), ('gagal', 'Gagal')], max_length=20)),
            ],
        ),
    ]
