# Generated by Django 5.0.3 on 2024-05-16 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0003_icreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icreation',
            name='isideskripsi',
            field=models.TextField(),
        ),
    ]
