# Generated by Django 5.0.3 on 2024-05-16 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0004_alter_icreation_isideskripsi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='icreation',
            name='isideskripsi',
        ),
        migrations.AddField(
            model_name='icreation',
            name='sub_deskripsi',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
