# Generated by Django 5.0.3 on 2024-05-29 09:54

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0005_remove_icreation_isideskripsi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelompok',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deskripsi', models.CharField(choices=[('Deskripsi fitur', 'Deskripsi fitur'), ('Deskripsi label', 'Deskripsi label')], max_length=100)),
                ('sub_deskripsi', models.CharField(blank=True, max_length=200, null=True)),
                ('kategori', models.CharField(choices=[('klasifikasi', 'Klasifikasi'), ('prediksi_numerik', 'Prediksi Numerik'), ('prediksi_probabilistik', 'Prediksi Probabilistik'), ('deteksi', 'Deteksi'), ('rekognisi', 'Rekognisi')], max_length=30)),
                ('tanggal_mulai_pemodelan', models.DateField()),
                ('tanggal_selesai_pemodelan', models.DateField()),
                ('status_penyelesaian', models.CharField(choices=[('selesai', 'Selesai'), ('berlangsung', 'Berlangsung'), ('gagal', 'Gagal')], max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='icreation',
            old_name='tanggal_mulai_pemodelan',
            new_name='tanggal_mulai',
        ),
        migrations.RenameField(
            model_name='icreation',
            old_name='tanggal_selesai_pemodelan',
            new_name='tanggal_selesai',
        ),
        migrations.RemoveField(
            model_name='icreation',
            name='deskripsi',
        ),
        migrations.RemoveField(
            model_name='icreation',
            name='kategori',
        ),
        migrations.RemoveField(
            model_name='icreation',
            name='sub_deskripsi',
        ),
        migrations.AddField(
            model_name='icreation',
            name='catatan_akhir',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='icreation',
            name='deskripsi_fitur',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icreation',
            name='deskripsi_label',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='icreation',
            name='deskripsi_masalah',
            field=models.TextField(default='Deskripsi default'),
        ),
        migrations.AddField(
            model_name='icreation',
            name='kategori_masalah',
            field=models.CharField(choices=[('Klasifikasi', 'Klasifikasi'), ('Prediksi Numerik', 'Prediksi Numerik'), ('Prediksi Probabilistik', 'Prediksi Probabilistik'), ('Deteksi', 'Deteksi'), ('Rekognisi', 'Rekognisi')], default='Klasifikasi', max_length=30),
        ),
        migrations.AddField(
            model_name='icreation',
            name='waktu_perekaman',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='icreation',
            name='waktu_update_terakhir',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='icreation',
            name='status_penyelesaian',
            field=models.CharField(choices=[('Selesai', 'Selesai'), ('Berlangsung', 'Berlangsung'), ('Gagal', 'Gagal')], default='Selesai', max_length=30),
        ),
    ]
