# Generated by Django 5.0.3 on 2024-05-30 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_entry', '0006_kelompok_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icreation',
            name='deskripsi_masalah',
            field=models.TextField(default=''),
        ),
    ]
